//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int Ma { get; set; }
        public int MaHD { get; set; }
        public string TenSP { get; set; }
        public int SoLuong { get; set; }
        public int GiaSP { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
