//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.HoaDon = new HashSet<HoaDon>();
        }
    
        public int Ma { get; set; }
        public string Ten { get; set; }
        public string SDT { get; set; }
        public int DiemTichLuy { get; set; }
        public int TongChiTieu { get; set; }
    
        public virtual ICollection<HoaDon> HoaDon { get; set; }
    }
}
