//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoNguyenLieu
    {
        public KhoNguyenLieu()
        {
            this.NguyenLieu = new HashSet<NguyenLieu>();
        }
    
        public int MaNL { get; set; }
        public string Ten { get; set; }
        public int SoLuong { get; set; }
        public string DonVi { get; set; }
    
        public virtual ICollection<NguyenLieu> NguyenLieu { get; set; }
    }
}
